insert into tenant (id, name) VALUES ('tenant1', 'tenant 1');
insert into auth_code_config (tenant_id, ttl, length) values ('tenant1', 900, 50);
insert into email_config (tenant_id, is_ssl_enabled, host, port, send_email_path, template_name, template_params) values ('tenant1', 0, 'mock', 6000, '/sendEmail', 'default', '{}');
insert into fb_config (tenant_id, app_id, app_secret) values ('tenant1', 'id', 'secret');
insert into google_config (tenant_id, client_id, client_secret) values ('tenant1', 'client-id', 'client-secret');
insert into otp_config (tenant_id, is_otp_mocked, whitelisted_inputs) values ('tenant1', 1, '{}');
insert into sms_config (tenant_id, is_ssl_enabled, host, port, send_sms_path, template_name, template_params) values ('tenant1', 0, 'mock', 6000, '/sendSms', 'default', '{}');
insert into token_config (tenant_id, algorithm, issuer, rsa_keys, access_token_expiry, refresh_token_expiry, id_token_expiry, id_token_claims, cookie_same_site, cookie_domain, cookie_path, cookie_secure, cookie_http_only, access_token_claims) values ('tenant1', 'RS256', 'https://test.com', json_array(json_object("current", "true", "kid", "test-kid", "private_key", "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAinYeXJY9uI5j9gnRYJxX/A0LCgVQ8NEfnghPzo75Vt6J+ijG\nOUkpyJ65p8VxztAwXO9200Ro3YSgP1sxluWS4Xj/aMbPbYcbFpFlDvZ9c1zjsFKy\ncUmOouz3fBump92qJoOcuKCoKmS5GZncC6hUKsTyp+0aUXMlKE7ViJaFtRgGmEfy\nHMlqr3o01cOH8lesyfAnrKcOtyNjAxlNR9E2S4HEBpT8fumYIVii5my55k8TWBaO\n+iEy4oNjSsRj4gxJvLnVRenXWE/l5gKVDipl98SVHWaCDRr5qFtDO0dwcXb9+Ep4\n2OTsBi8q2XcHTfsyfX/sClAMQtBmAemmdS5kEQIDAQABAoIBADISTSCGZIOdWqDb\nJBCf+WF5Bgj1qzOrLJflwZadNaYojBUfMa/9uVKHs/Pr/yAfQZ4aKwpzrsiM8bZ3\nsBM1qkxHiXXGj7S4Kx+aLMWgdfWGHgDhpw4435Ajycvj4/zIuIN9DOvnjWjnS9jq\nPx0oHmfpGSeJIv9ZeJJ/D9F5PZkjLUFAjaipjlrgV38PCFYryb+pcwPsLrJ/Su56\nz4DL4u2R9Nw7RQcuqrbN/gAkQlMah9UOBW3P8Pob4k30RCtP1mBX6HztYoCC75VM\norLFgHcmOBz4SilA5QFADl8ruAc2lEwJiBwpAOsSVUCfZIZKzXkSQf2jAIjDlIRH\n6WqQvhECgYEA+y0x+x+ByCYLeWe+/gcB5s9YbMYTPzcJqzGVVg5rI4fhatuP+tEX\ncfPR7+RzcvlOKhpcj7+KqUKUiYPJ8RH49dQuEpcuBJPX243l1tosuV+JwwZVpDtn\nQcuH/2dxxGu3Cx7cw2OkgJ/lpQHUwFq7DAIZFj3JsMlNRf2KQ2MVc8sCgYEAjR7O\nbRp+/k2mAttj0PAsQKYWxbAEE5vGRTcIVGzoY0krO1Ttv2qjP9OmA/RAtuGhhadu\n9pbc5Cn4IrvNnsI0wGYJcJ+4gKd2LnZl2UzVJ43UxjeNkg+go7+QFSEb5D74d+Xa\nMwqxF1GDSWhIeytA+UoE8FQ5/M+qTLzRTgui5BMCgYBjGWzL2J1620/RoZYgYaFl\ncE9B81Bqs4tUCOcTofKxfQ35/BCtc8udQQaGcIsARM6LHAWDDZ5ms4cpTl7hhybD\nzugym4UjdzVGQZD6GPBmXwRaduhZOLq/oc7RfP3M8nawo4eUa37e5LdVSAipr+J2\nlWlSdiRaZMHhKGxhs/klywKBgBRqVYCxKZgOkaquJHWQmUZNANRej2hqy7ctq/XS\nv5fFeQyfT7m2aqGMM+M0jbwnTh+wxjvEPXaAn9YehzOlcs42tLznTmDGWTGFjVxv\nYhLT0OlQFhoASsQFrYlw/cD6XyWxSezCajYuY6jV/k5bRo4J6EcAWFc7j66ETl9V\nDZ6jAoGBAMH8m80u6bhLBxcr8y5n89VtglNFZ7eg6Y9ZKOTBeXG0DFXKN7ZVZ26Z\n4+nNITgldxasLQYKrvuSi/j9rkkV5GzzYWfZR38CNb2WxaJy0DNp0eH3L5T3ywkh\nIhPWp56/sF46YfFYfTH6b2diJf3NFETfYcX1f+39hfGANY+LKzuV\n-----END RSA PRIVATE KEY-----", "public_key", "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAinYeXJY9uI5j9gnRYJxX\n/A0LCgVQ8NEfnghPzo75Vt6J+ijGOUkpyJ65p8VxztAwXO9200Ro3YSgP1sxluWS\n4Xj/aMbPbYcbFpFlDvZ9c1zjsFKycUmOouz3fBump92qJoOcuKCoKmS5GZncC6hU\nKsTyp+0aUXMlKE7ViJaFtRgGmEfyHMlqr3o01cOH8lesyfAnrKcOtyNjAxlNR9E2\nS4HEBpT8fumYIVii5my55k8TWBaO+iEy4oNjSsRj4gxJvLnVRenXWE/l5gKVDipl\n98SVHWaCDRr5qFtDO0dwcXb9+Ep42OTsBi8q2XcHTfsyfX/sClAMQtBmAemmdS5k\nEQIDAQAB\n-----END PUBLIC KEY-----")), 900, 86400, 3600, json_array(), "NONE", "test.com", "/", false, true, json_array());
insert into user_config (tenant_id, host, port, is_ssl_enabled, get_user_path, create_user_path, authenticate_user_path, add_provider_path, update_user_path) values ('tenant1', 'mock', 6000, 0, '/user', '/user', '/authenticateUser', '/provider', '/user');
insert into contact_verify_config (tenant_id, is_otp_mocked, whitelisted_inputs) values ('tenant1', 1, '{}');
insert into admin_config (tenant_id, username, password) values ('tenant1', 'admin', 'admin123');


insert into scope (tenant_id, name, display_name, description, icon_url, claims, is_oidc) values ('tenant1', 'profile', 'Profile', 'Profile scope for user information', "", json_array("name", "family_name", "given_name"), 1);
insert into scope (tenant_id, name, display_name, description, icon_url, claims, is_oidc) values ('tenant1', 'default', 'default', 'default scope for access', "", json_array(), 0);
insert into oidc_config (tenant_id, issuer, authorization_endpoint, token_endpoint, userinfo_endpoint, revocation_endpoint, jwks_uri, grant_types_supported, response_types_supported, subject_types_supported, id_token_signing_alg_values_supported, token_endpoint_auth_methods_supported, login_page_uri, consent_page_uri, authorize_ttl) VALUES ('tenant1', 'https://auth.example.com', 'https://auth.example.com/oauth2/authorize', 'https://auth.example.com/oauth2/token', 'https://auth.example.com/userinfo', 'https://auth.example.com/oauth2/revoke', 'https://auth.example.com/.well-known/jwks.json', JSON_ARRAY('authorization_code', 'refresh_token'), JSON_ARRAY('code'), JSON_ARRAY('public'), JSON_ARRAY('RS256'), JSON_ARRAY('client_secret_basic', 'client_secret_post'), 'https://auth.example.com/login', 'https://auth.example.com/consent', 600);

insert into client (tenant_id, client_id, client_secret, client_name, client_uri, contacts, grant_types, logo_uri, policy_uri, redirect_uris, response_types, client_type, is_default) values ('tenant1', 'client-id', 'client-secret', 'Test Client', 'https://test.com', json_array(''), json_array('authorization_code', 'refresh_token'), 'https://test.com/logo.png', 'https://test.com/policy', json_array('https://test.com/callback'), json_array('code'), 'third_party', false);
insert into client (tenant_id, client_id, client_name, client_secret, client_uri, contacts, grant_types, logo_uri, policy_uri, redirect_uris, response_types, client_type, is_default) values ('tenant1','client1','Test Client App','s3cr3tKey123','https://clientapp.example.com',JSON_ARRAY('admin@example.com','support@example.com'),JSON_ARRAY('authorization_code','refresh_token','client_credentials'),'https://clientapp.example.com/logo.png','https://clientapp.example.com/policy',JSON_ARRAY('https://clientapp.example.com/callback','https://clientapp.example.com/redirect'),JSON_ARRAY('code'),'first_party',TRUE);
insert into client (tenant_id, client_id, client_name, client_secret, client_uri, contacts, grant_types, logo_uri, policy_uri, redirect_uris, response_types, client_type, is_default) values ('tenant1','client2','Test Client App','s3cr3tKey123','https://clientapp.example.com',JSON_ARRAY('admin@example.com','support@example.com'),JSON_ARRAY('authorization_code','refresh_token','client_credentials'),'https://clientapp.example.com/logo.png','https://clientapp.example.com/policy',JSON_ARRAY('https://clientapp.example.com/callback','https://clientapp.example.com/redirect'),JSON_ARRAY('code'),'first_party',TRUE);
insert into client_scope (tenant_id, client_id, scope) values ('tenant1', 'client-id', 'profile');
insert into client_scope (tenant_id, client_id, scope, is_default) values ('tenant1', 'client1', 'default', TRUE);
insert into client_scope (tenant_id, client_id, scope, is_default) values ('tenant1', 'client2', 'default', TRUE);
insert into guest_config(tenant_id, is_encrypted, secret_key, allowed_scopes) values ('tenant1', true, '2CmxIQJd8UJWAdm8',JSON_ARRAY('profile', 'email', 'phone'));

UPDATE client SET mfa_policy = 'not_required', allowed_mfa_methods = NULL WHERE tenant_id = 'tenant1' AND client_id = 'client-id';
UPDATE client SET mfa_policy = 'mandatory', allowed_mfa_methods = JSON_ARRAY('password', 'pin', 'sms-otp', 'email-otp') WHERE tenant_id = 'tenant1' AND client_id = 'client1';
UPDATE client SET mfa_policy = 'not_required', allowed_mfa_methods = JSON_ARRAY('password', 'pin', 'sms-otp', 'email-otp') WHERE tenant_id = 'tenant1' AND client_id = 'client2';
